import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/molecules/Navbar";
import Container from "@/components/atoms/Container";
import { Toaster } from "react-hot-toast";
import { navSchema } from "./utils/constants";

import { Providers } from "./provider";
import Footer from "@/components/molecules/Footer";
import AgeVerification from "@/components/organisms/AgeVerification";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fi_Fi" suppressHydrationWarning={true}>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(navSchema) }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AgeVerification />
        <Providers>
          <Container>
            <Navbar />
            {children}
          </Container>
          <Footer />
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
